#!/bin/bash

help=$(cat << EOF
usage [run <command>]
watch   start tests in watch mode
ci      run ci commands
scope   run app
EOF
)

cmd=$1
shift

case "$cmd" in
    watch)
        cargo watch -x test ;;
    ci)
        cargo fmt --all
        cargo clippy --workspace --all-targets -- -D warnings
        cargo test --workspace
        ;;
    scope)
        cargo run -- "$@"
        ;;
    *) echo "$help"
esac
